### ISSUE TITLE
Validation profile (Italian, Security, ...) should be visible

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#112]
## I expect

Validation profile to be visible, as this is an input value for the validation process

## Instead

It is not.

## Note

It could be worth even allowing to change the profile without switching to the hamburger view

cc: @fupete

**Comment by emilioSp** [comment]
I've implemented it on the validation button as a quick fix. It is always visible.

![image](https://user-images.githubusercontent.com/22614105/103357448-82439280-4ab3-11eb-9a7c-9755e4401222.png)

**Comment by ioggstream** [comment]
I like it. @fupete have your say.

**Comment by Fupete** [comment]
We can use our 'italian UI' <select> ➡️  https://italia.github.io/design-react-kit/?path=/story/componenti-form-select--select-con-gruppi 
To save vertical space maybe we can try to remove the upper label write a GROUP label inside like: "CHOOSE VALIDATION PROFILE".  cc @emilioSp @ioggstream
