### ISSUE TITLE
Every rule should have a description

### ISSUE THREAD

**Issue by emilioSp** [italia/api-oas-checker#122]
# I expect

A description field that explains the rule.

# Instead

Some rules don't have a description. ([ex.1](https://github.com/italia/api-oas-checker/blob/master/rules/schemas.yml#L2), [ex.2](https://github.com/italia/api-oas-checker/blob/master/rules/metadata.yml#L111))

**Comment by ioggstream** [comment]
we need to test that.

**Comment by emilioSp** [comment]
I'll make fail the build if a description is not provided.

In the meanwhile could you fix [this](https://github.com/italia/api-oas-checker/blob/master/rules/oas3only.yml#L2)?

**Comment by ioggstream** [comment]
This is non trivial... I have to investigate. Pls ignore 'false' rules in the processing

**Comment by ioggstream** [comment]
fixed.
