### ISSUE TITLE
Larger modal width for rule description

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#147]
## I expect

The modal window to be a bit larger (eg. `.modal-content, .modal-header:{ 750px;} `?). See

![image](https://user-images.githubusercontent.com/1140844/104725468-6cc89c80-5732-11eb-80a0-4875ab8df04e.png)

cc: @fupete

**Comment by Fupete** [comment]
I think you just need to add the class 
`modal-lg`
to your modal.

Eg: 
![immagine](https://user-images.githubusercontent.com/6736103/104763026-9bac3600-5765-11eb-8e10-a11159d34c99.png)

Reference: 
https://italia.github.io/bootstrap-italia/docs/componenti/modale/#dimensioni-opzionali

@ioggstream ;-)

**Comment by Fupete** [comment]
Auto-review: there is also a larger `modal-xl` class available from Bootstrap.

**Comment by Fupete** [comment]
Ref. issue https://github.com/italia/bootstrap-italia/issues/666 on Bootstrap Italia.
