### ISSUE TITLE
Waring no-x-headers-response with X-Correlation-ID

### ISSUE THREAD

**Issue by tilox83** [italia/api-oas-checker#235]
if an API declares the following header 
`"X-Correlation-ID" : {
        "description" : "xxxxx",
        "schema" : {
          "type" : "string"
        }
      }`
it is reported as a warning:
`HTTP response header SHOULD NOT start with 'X-' in #/paths/......./get/responses/200/headers/X-Correlation-ID`

**Comment by ioggstream** [comment]
Provide a whitelist for x-headers defined in MODI
