### ISSUE TITLE
Improve the webapp design

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#3]
## I expect

the webapp design to be improved 
using the design guidelines

cc: @fupete

**Comment by Fupete** [comment]
I have a couple of ideas...

**Comment by Fupete** [comment]
Here you can find an idea of interface and logo ➡️ [Invision prototype](https://invis.io/28ZM8ML47PT#/439475618_0-Initial-State)

Click the invisible buttons or use L-R arrows keys to navigate between the 5 mockups, last one is just the logo/mark.
On the right-down corner of your viewport you have comments and access to inspect tools. 

Mockups index: 
- Initial State
- Validating Processing
- Validation Results
- Validation Results with Closed Menu

**Consider this a draft. Feedbacks are welcome.**
