### ISSUE TITLE
securitySchemes.yml refers to PUT and DELETE non-idempotent operations 

### ISSUE THREAD

**Issue by savage-alex** [italia/api-oas-checker#445]
Hi,

Firstly the security rule is brilliant! I have been working on a custom function for it but yours just works!!

What confused me a little was the comment that you should have more security for non-idempotent operations " HTTP methods like `POST`, `PUT`, `PATCH` and `DELETE`." But I thought PUT and DELETE were idempotent. Did you mean SAFE verbs rather than Idempotent? 

Thanks for your time

**Comment by ioggstream** [comment]
Hi @savage-alex! That's correct :) Can you please make a PR for that?

**Comment by savage-alex** [comment]
will certainly do! thanks

**Comment by savage-alex** [comment]
https://github.com/italia/api-oas-checker/pull/446 resolves this issue

**Comment by ioggstream** [comment]
Thanks @savage-alex !
