### ISSUE TITLE
Enforcing proper response bodies

### ISSUE THREAD

**Issue by savage-alex** [italia/api-oas-checker#453]
Hi,

2 rules we have that may be of interest to you:  (NB You may wish to reduce the severity)

adv-response-body-200x:
    description: All 200x responses except for 204 MUST include a response body
    message: >-
      HTTP response {{path}} MUST have a response body. All 200x (except 204)
      responses MUST have a response body. If a body is not needed, use 204 instead.
    severity: error
    given: "$.paths.[?( @property === '200' || @property === '201'
      || @property === '202')]"
    then:
      field: content
      function: truthy

  adv-response-204-no-body:
    description: All 204 responses MUST NOT have a response body.
    message: HTTP response {{path}} MUST NOT have a response body. All 204 responses MUST NOT have a response body.
    severity: error
    given: $.paths.[?( @property === '204')]
    then:
      field: content
      function: falsy

**Comment by ioggstream** [comment]
Hi @savage-alex ! Thank you! Can you try to create a PR when you've some time?

Which is your experience with the repo layout? Do you feel contribution is easy or clumsy?

These days I'm experimenting with spectral-6.1 but I found some issues in porting the existing ruleset (eg. see https://github.com/stoplightio/spectral/issues/1920#issuecomment-975538350 )...

**Comment by savage-alex** [comment]
We sadly had the same with spectral 6. Some work is going to be needed there.

**Comment by ioggstream** [comment]
Ok, so you don't have a separate CI to validate ruleset (eg. gh-actions).

**Comment by savage-alex** [comment]
We have spectral running as a gh-action to ensure no openapi defs are checked in with problems. The rules themselves have jest tests but we are yet to add an action for that to prevent breaking rules (something I want !)

**Comment by ioggstream** [comment]
@savage-alex PTAL https://github.com/italia/api-oas-checker/pull/489
