### ISSUE TITLE
Stop validation asap if tab `\t` is present

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#52]
## Reproduce

the `tab` character may break validation, and it's quite difficult to troubleshoot that

## I expect

- [ ] The web ui validation to failfast on `tabs`
- [ ] the tab characters to be highlighted

**Comment by peppelinux** [comment]
Which behaviour would you like to have with this,
Should the checker remove the \t and continue with validation or invalidate the schema marking that byte like an error?

I would like the First, more flexible in a real scenario, approach but probably you would like the second. A regexp would reach the goal, any clue?

**Comment by ioggstream** [comment]
Hi @peppelinux, I think at first we should make it simple, so:

1a- no validation is run if tabs are present;
1b- an error should be displayed on the right pane;
2- tabs should be highlighted (probably there's already some codemirror builtin here https://codemirror.net/demo/visibletabs.html);
3- user can remove tabs manually;
4- user can trigger a new validation clicking on the validatio button.

In the meanwhile, a preliminary patch with 1a and 1b is ok.

Consider that the *production* scenario is the one where checks are run via CI, so the editor shouldn't modify tabs automatically (at least for now :))

**Comment by ioggstream** [comment]
Closed in favor of #116
