### ISSUE TITLE
Success validation when input file doesn't exist

### ISSUE THREAD

**Issue by vlauciani** [italia/api-oas-checker#60]
I use `api-oas-checker` by docker.

When I try to validate an input file into a not existing directory, the return code is `0`, `success`. For example:
```
$ docker run --rm -v $(pwd)/pippoPlutoPaperino:/tmp stoplight/spectral lint -r https://teamdigitale.github.io/api-oas-checker/spectral.yml "/tmp/oa3.yaml"
No results with a severity of 'error' or higher found!

$
$ echo $?
0
$
```
but the local directory `$(pwd)/pippoPlutoPaperino` doesn't exist. This means that the PipeLine doesn't fail.

**Comment by ioggstream** [comment]
It's the spectral behavior... Let's ask there.

**Comment by ioggstream** [comment]
@vlauciani To ensure that a file has been processed we should verify that the output starts with  `OpenAPI 3.x detected`. This could probably affect the action.
