### ISSUE TITLE
gh-pages target in Makefile never removes files

### ISSUE THREAD

**Issue by bfabio** [italia/api-oas-checker#61]
The [`gh-pages` target](https://github.com/teamdigitale/api-oas-checker/blob/master/Makefile#L22) never removes locally deleted files in production, if any.

**Comment by ioggstream** [comment]
@bfabio can we close? This is probably stale now for the new-ui branch

**Comment by bfabio** [comment]
@ioggstream not yet, it's still valid for the new-ui branch but @emilioSp added [a todo comment](https://github.com/italia/api-oas-checker/blob/feat/new-ui/Makefile#L53). Once it's fixed there we can add the `done` and `new-ui` labels.
