### ISSUE TITLE
application/problems+json check failing to recognised bad schemas

### ISSUE THREAD

**Issue by savage-alex** [italia/api-oas-checker#627]
When I lint the following openAPI (with a purposely wrong schema for application/problem+json it is not reported as failing
https://app.swaggerhub.com/apis/AdvancedComputerSoft/ApplicationProblemJsonTest/1.0.1

**Comment by ioggstream** [comment]
See #628

**Comment by ioggstream** [comment]
@savage-alex is this fixed?

**Comment by savage-alex** [comment]
Yes works great now thank you
