### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by AlessioMarinelli** [italia/api-oas-checker#690]
Are there any rules (or at least best practices) about pagination on GET requests?

I can find only #145 about this, but no rules in the checker (https://github.com/italia/api-oas-checker/blob/master/rules/pagination.yml is empty)

**Comment by ioggstream** [comment]
Hi @AlessioMarinelli, we can follow up on #145 

See https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/doc_02_cap_04.html#uniformita-e-naming

**Comment by AlessioMarinelli** [comment]
Thanks!
