### ISSUE TITLE
Align the Editor and Error views

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#75]
## Reproduce

1- open https://teamdigitale.github.io/api-oas-checker/
2- lint the default api clicking on "Lint URL" using the "Extra security checks" profile
3- scroll down the error list

## I expect

the editor view to not disappear when scrolling down the error list

## Instead

the editor view disappears 

@bfabio

**Comment by bfabio** [comment]
Can you add more details on what this is about @ioggstream ?

**Comment by ioggstream** [comment]
@emilioSp is this fixed in the new ui?

**Comment by emilioSp** [comment]
Yes! In the new ui the editor is always visible and the error list is scrollable

**Comment by ioggstream** [comment]
Pls define a policy for closing tickets which are completed in the new UI (Eg link them and close, ...)

Probably many of the open ones can be closed just now

**Comment by emilioSp** [comment]
We have added 2 labels

- new-ui
- done

When we will deploy the new ui, we will close all the done issues.
