### ISSUE TITLE
Rules dropdown switch should not trigger linting

### ISSUE THREAD

**Issue by sebbalex** [italia/api-oas-checker#77]
As of now switching profile rules will trigger the linter and validation process begins.
I think, for a better usability, that Lint must be triggered manually and let user to control this.

wdyt @ioggstream

**Comment by ioggstream** [comment]
### example

- I change the select from "Default" to "Security" ruleset
- the app does not re-lint

Then

1- the view shows the "Default" error list
2- the select shows the "Security" ruleset

### Note

if we don't want to trigger, we should at least cleanup the results

**Comment by sebbalex** [comment]
> example
I change the select from "Default" to "Security" ruleset
the app does not re-lint

I cannot verify this, could you please double check?

>Note
if we don't want to trigger, we should at least cleanup the results.
Before cleanup, we can let people download the validation output #78

I totally agree

**Comment by ioggstream** [comment]
> I cannot verify this, could you please double check?

example of an hypothetical behavior not triggering a lint ;)

**Comment by ioggstream** [comment]
@emilioSp @sebbalex is this actual?

**Comment by emilioSp** [comment]
No, it's not actual.
I close the issue because in the new ui the validation trigger is lead by the validate button together with the auto-refresh trigger
